### PR TITLE
Fixed the autoplay img slider

### PR DESCRIPTION
**Pull request by biswarup-naha**

### CODE REVIEW

**Comment by AyishikD** [comment]
@biswarup-naha Change something meaningful it would be better . You have just wrote my code without camel case.

**Comment by biswarup-naha** [comment]
@AyishikD the slider was not working in the original code since the camel case isn't accepted as a method. I've tried implementing another sliding animation but the original one just looks better.
Okay, I'm giving it another shot let's see if something more meaningful can be made.

**Comment by AyishikD** [comment]
Work progress @biswarup-naha ??

**Comment by biswarup-naha** [comment]
@AyishikD I've updated the image slider to a whole new carousel effect. Extremely sorry for not responding, we were having sem exam :'( . I can make a PR that you may review.

**Comment by AyishikD** [comment]
> @AyishikD I've updated the image slider to a whole new carousel effect. Extremely sorry for not responding, we were having sem exam :'( . I can make a PR that you may review.

Make a new PR

**Pull request closed without merging**
