### PR TITLE
Scroll bar added

### PR DESCRIPTION
**Pull request by Souvik34**
Issue #30 
Scroll bar added with color gradients matching with the logo.

### CODE REVIEW

**Comment by AyishikD** [comment]
@Souvik34 resolve merge conflict

**Comment by Souvik34** [comment]
Resolved

**Comment by AyishikD** [comment]
@Souvik34 deployment failed

**Comment by Souvik34** [comment]
Fixed the errors

**Comment by AyishikD** [comment]
@Souvik34 Fix the navbar u have changed it

**Pull request closed without merging**
