### PR TITLE
nav responsiveness add

### PR DESCRIPTION
**Pull request by Soumojitshome2023**
nav responsiveness add

# Before : 
Screenshot (496)

# After : 
image

### CODE REVIEW

**Comment by AyishikD** [comment]
@Soumojitshome2023 all icons came in one place in mobile view

**Comment by AyishikD** [comment]
Also in every view login has moved to the left side

**Comment by Soumojitshome2023** [comment]
Yas so?

**Comment by Soumojitshome2023** [comment]
Now its okay??? 

image

**Pull request merged**
